spring:
#  cache:
#    type: redis
  security:
    oauth2:
      resourceserver:
        jwt:
          # Đặt địa chỉ JWK Set của Authorization Server tại đây
          jwk-set-uri: http://localhost:9000/oauth2/jwks
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope: openid,profile,email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  datasource:
    #    url: jdbc:mysql://localhost:3306/read_model_db?useSSL=false&allowPublicKeyRetrieval=true
    #    username: root
    #    password: 123456
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/auth_service_event-sourcing_db # Địa chỉ kết nối đến PostgreSQL
    username: postgres # Tên người dùng mặc định của PostgreSQL thường là postgres
    password: 123456 # Thay bằng mật khẩu PostgreSQL của bạn
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect