spring:
  kafka:
    # 1. Cấu hình Producer (để gửi tin nhắn đến Kafka)
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      batch-size: 16384 # bytes
      linger-ms: 10 # milliseconds

    # 2. Cấu hình Consumer (để nhận tin nhắn từ Kafka)
    consumer:
      bootstrap-servers: localhost:9092
      group-id: read-model-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval-ms: 1000

  # 3. Cấu hình để connection với database
  datasource:
    #    url: jdbc:mysql://localhost:3306/read_model_db?useSSL=false&allowPublicKeyRetrieval=true
    #    username: root
    #    password: 123456
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/read_model_db
    username: postgres # Tên người dùng mặc định của PostgreSQL thường là postgres
    password: 123456 # Thay bằng mật khẩu PostgreSQL của bạn
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082