spring:
  kafka:
    # 1. Cấu hình Producer (để gửi tin nhắn đến Kafka)
    producer:
      bootstrap-servers: localhost:9092
      # Phương thức serialize key của message
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Phương thức serialize value của message
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer # Hoặc StringSerializer, ByteArraySerializer tùy dữ liệu
      acks: 1
      batch-size: 16384 # bytes
      linger-ms: 10 # milliseconds

    # 2. Cấu hình Consumer (để nhận tin nhắn từ Kafka)
    consumer:
      bootstrap-servers: localhost:9092
      group-id: command-service-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval-ms: 1000 # milliseconds

    # 3. Cấu hình để connection với database
    datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=command-cv-management;encrypt=true;trustServerCertificate=true
      username: An
      password: 1
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
server:
  port: 8082